language: en-US
early_access: false
reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: true
  path_instructions:
    - path: "**"
      instructions: |
        - CONTEXT: Vue 3 SPA — SRE dashboard (health probes, chaos controls, API explorer)
        - This is a learning/reference app, not a production product — keep it simple
        - KISS principle: simple > complex in all decisions
        - Be strict on: security vulnerabilities, hardcoded secrets/URLs, XSS risks
        - Be fair on: established patterns, component structure for demo views
    - path: "src/**/*.{vue,js}"
      instructions: |
        - Vue 3 with Composition API, Pinia state management, Vue Router 4
        - Tailwind CSS v4 (CSS-first config, no tailwind.config.js)
        - Runtime config via window.__ENV__ — never hardcode API URLs or env values
        - Axios client in services/api.js — all backend calls go through this
        - OpenTelemetry browser SDK for tracing
        - Check: no hardcoded URLs or environment-specific values
        - Check: proper error handling in API calls
        - Check: no console.log in production code (except api.js interceptors)
    - path: "Dockerfile"
      instructions: |
        - Multi-stage build: node:alpine builder → nginx:alpine runtime
        - Must run as non-root user (appuser, uid 10001)
        - Runtime config generated by entrypoint script (40-generate-env-config.sh)
        - Check: no unnecessary packages in runtime stage
        - Check: /config.js served from /tmp with no-cache headers
    - path: "nginx/**"
      instructions: |
        - SPA routing: all routes fall back to index.html
        - /config.js served from /tmp/config.js (runtime-generated, no-cache)
        - /health endpoint for container health checks
        - Check: security headers present (X-Frame-Options, X-Content-Type-Options)
        - Check: static assets have long cache, HTML/config have no-cache
    - path: "**/.github/workflows/*.yml"
      instructions: |
        - build.yml: multi-platform Docker build (amd64+arm64), GHCR push, Trivy scan
        - promote-production.yml: re-tag staging→production (no rebuild), Trivy gate, GitHub Release
        - Check: Trivy scan is non-blocking in build, blocking for production promotion
        - Check: image tags follow convention (env-version-sha-timestamp)
        - Check: proper secret handling, no secrets in logs
    - path: "**/CLAUDE.md"
      instructions: |
        - Repository guidelines for AI agents — learn and apply these principles
  path_filters:
    - "src/**/*.vue"
    - "src/**/*.js"
    - "**/Dockerfile"
    - "nginx/**"
    - "**/.github/workflows/*.yml"
    - "**/CLAUDE.md"
    - "!**/node_modules/**"
    - "!**/dist/**"
  tools:
    gitleaks:
      enabled: true
    semgrep:
      enabled: true
    hadolint:
      enabled: true

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CLAUDE.md"
  learnings:
    scope: "local"
  issues:
    scope: "local"
  pull_requests:
    scope: "local"

chat:
  auto_reply: false
tone_instructions: "KISS principle: simple > complex. This is a reference/learning SPA — focus on security, clean Vue patterns, and proper runtime config. Skip over-engineering suggestions."
